"""Browser UI command."""

import json
import sys

import click

from cli.core import StudioAPI, console, get_frontend_port

try:
    from playwright.sync_api import sync_playwright
except ImportError:
    sync_playwright = None  # type: ignore[assignment, misc]


@click.command()
@click.argument("file_id", type=int)
@click.option("--playwright", is_flag=True, help="Output Playwright script instead of opening browser")
def ui(file_id: int, playwright: bool) -> None:
    """Open browser to file with logged-in session, or output Playwright script."""
    if sync_playwright is None:
        console.print("[red]✗ playwright is not installed. Run: pip install rsm-studio-cli[dev][/red]")
        sys.exit(1)

    api = StudioAPI()

    if not api.session.is_valid():
        console.print("[red]✗ Not logged in. Run 'studio login' first.[/red]")
        sys.exit(1)

    session_data = api.session.load()
    if not session_data:
        console.print("[red]✗ Session data corrupted.[/red]")
        sys.exit(1)

    frontend_port = get_frontend_port()
    frontend_url = f"http://localhost:{frontend_port}"
    file_url = f"{frontend_url}/file/{file_id}"

    if playwright:
        user_json = json.dumps(session_data["user"]).replace("'", "\\'")
        access_token = session_data["access_token"]
        refresh_token = session_data["refresh_token"]

        # Build JavaScript as a single line to avoid wrapping issues
        js_code = (
            f"localStorage.setItem('accessToken', '{access_token}'); "
            f"localStorage.setItem('refreshToken', '{refresh_token}'); "
            f"localStorage.setItem('user', '{user_json}');"
        )

        script = f"""# Auto-generated Playwright script for file {file_id}
# Generated by: studio ui {file_id} --playwright

from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch(headless=False)
    page = browser.new_page()

    # Navigate to frontend
    page.goto('{frontend_url}')

    # Inject session tokens
    page.evaluate('''{js_code}''')

    # Navigate to file
    page.goto('{file_url}')

    # ADD YOUR TEST CODE BELOW
    # Example:
    # page.click('[data-testid="some-button"]')
    # page.fill('[data-testid="input"]', 'test value')
    # assert page.locator('[data-testid="result"]').text_content() == 'expected'

    browser.close()
"""
        # Use print() instead of console.print() to avoid Rich's automatic line wrapping
        # which breaks the JavaScript code in page.evaluate()
        print(script)
        return

    console.print(f"[cyan]Opening browser to file {file_id}...[/cyan]")

    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=False)
            page = browser.new_page()

            page.goto(frontend_url)

            page.evaluate(
                """({ accessToken, refreshToken, user }) => {
                    localStorage.setItem('accessToken', accessToken);
                    localStorage.setItem('refreshToken', refreshToken);
                    localStorage.setItem('user', JSON.stringify(user));
                }""",
                {
                    "accessToken": session_data["access_token"],
                    "refreshToken": session_data["refresh_token"],
                    "user": session_data["user"],
                },
            )

            page.goto(file_url)

            console.print(f"[green]✓ Browser opened to {file_url}[/green]")
            console.print("[dim]Browser will stay open. Close manually when done.[/dim]")

    except Exception as e:
        console.print(f"[red]✗ Browser error: {e}[/red]")
        sys.exit(1)
